version: '3.8'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/poll/static
    ports:
      - 1337:80
    depends_on:
      - poll
  poll:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn rcfbpoll.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/poll/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
  static_volume: